name: Docker Compose Actions Workflow
on: push
branches:
  - main
  - api-features
  - dependabot
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the images and start the containers
        run: docker-compose up -d --build
     - name: Stop containers
       if: always()
       run: docker-compose -f "docker-compose.yml" down

